name: CI

on:
  push:
    branches:
      - master
      - blas
  pull_request:
    branches:
      - master
      - blas
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install OpenBLAS
        run: sudo apt-get install -y libopenblas-dev
      - name: Lean Action
        uses: leanprover/lean-action@v1
        with:
          build-args: "--log-level=error"
      - name: Run Tests
        run: lake test
      - name: Run Examples
        run: make examples
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install OpenBLAS
        run: choco install openblas
      - name: Lean Action
        uses: leanprover/lean-action@v1
        with:
          build-args: "--log-level=error"
      - name: Run Tests
        run: lake test
      - name: Run Examples
        run: make examples
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install OpenBLAS
        run: brew install openblas
      - name: Lean Action
        uses: leanprover/lean-action@v1
        with:
          build-args: "--log-level=error"
      - name: Run Tests
        run: lake test
      - name: Run Examples
        run: make examples
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'